source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXAutoRollLabel_Example', :exclusive => true do
  pod 'BXAutoRollLabel', :path => '../'
end

target 'BXAutoRollLabel_Tests', :exclusive => true do
  pod 'BXAutoRollLabel', :path => '../'

  
end
