source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXAutoRollLabel_Example' do
  pod 'BXAutoRollLabel', :path => '../'
end

target 'BXAutoRollLabel_Tests' do
  pod 'BXAutoRollLabel', :path => '../'

  
end
